### ISSUE TITLE
Comentarios QMP - Entrega 2

### ISSUE THREAD

**Issue by PalumboN** [GuidoMartinez/DDS-QueMePongo#1]
Hola @GuidoMartinez , te dejo algunos comentarios sobre la entrega 2 de QMP que fue el viernes pasado, disculpas por la demora.

En términos generales la entrega está muy bien. Me gustaron los comentarios que dejaste en el README, hago algunas aclaraciones para seguir mejorando:

> En la siguiente iteracion, en caso de exitir un Usuario, se podria guardar en lista del mismo. Por el momento al no necesitar testear el Repositorio de borradoresPrenda, no me genera inconvenientes el patron utilizado.

- Aunque aparezca un usuario, por lo general no se guardan las entidades asociados al mismo en el objeto. No hay que confundir actor del sistema (persona real) con el modelo de objetos. En ese contexto, lo que posiblemente pasará es que al repositorio de borradores se le pedirá los borradores de un usuario en particular.
- No sé por qué no testearías el repo de borradores. Ahora quizá tenga una lógica muy sencilla, pero como todo componente sí se puede (y deberíamos tener) testear unitariamente. 
- Tampoco entiendo por qué te generaría inconvenientes el testing. 

> El siguiente requerimiento se cumple controlando el momento de la creacion de la prenda a traves del BorradorPrenda por medio de la UI

- Acá se está tomando una decisión de arquitectura, cosa que todavía no vimos, así que hay que tener cuidado con decidir algo muy fuerte. 
- De todas formas, por más que pongas la validación en la UI, de alguna forma hay que implementarlo, y no se aclara nada sobre cómo se haría esa validación. De hecho, faltan relaciones entre entidades de dominio (las cuales sí se detallan) para poder hacer esa validación.
- O sea, está bien pensar en estas cosas, pero el decidir poner la lógica en otro módulo/nodo de la aplicación no evita que tengamos que resolver el requerimiento. Acá quedó como fuera de alcance y no lo era.

> Entiendo que apunta a los predefinidos en el enunciado (San Juan y Johnson), en caso de requerir armar nuevos uniformes en base a las prendas cargadas, no especifica si hay algun criterio o se deben elegir aleatoriamente una de cada tipo (superior, inferior, calzado) de un grupo/repo de prendas ya creadas.

- En realidad esos "predefinidos" son ejemplos de usos. Lo que se debe sacar como requerimientos es que el sistema debe permitir armar uniformes para sugerirlos y permitir a cada institución crear uno(s).
- No se especifica ningún criterio porque no hay reglas (más que la que consta de 3 partes) para el armado de un uniforme, lo decide y arma una persona.
- "elegir aleatoriamente una de cada tipo" sería otro ejemplo de uso, bastante particular y raro dado el contexto en el que se está analizando el sistema.

-----

Después respecto al código y diagrama están muy bien ambos (sin contar el detalle de la falta de validación comentada anteriormente). Como únicos comentarios tengo:

https://github.com/GuidoMartinez/DDS-QueMePongo/blob/ae2ca080b56c5ce9e69286994fe49c2fcf14b72d/src/main/java/Uniforme.java#L14-L18

- Es raro que este método esté en la clase de Uniforme. Si es el Diseñador el que sabe crear cada una de las partes, no sería mejor poder pedirle directamente el uniforme creado y mantener una interfaz más simple?
- No habría que validar en algún momento que las prendas que se crean son de la categoría que dicen ser?

Saludos!!

**Comment by GuidoMartinez** [comment]
Buenas @PalumboN , gracias por el feedback!

Te consulto sobre algunas dudas que me quedaron:
- Sobre el repo de BorradoresPrenda, clarísimos los puntos. La "dificultad" del testing venía por implementarlo como Singleton en vez de inyectar la dependencia (lo vemos en la clase del próximo viernes).

- Sobre la configuracion del BorradorPrenda en el Builder

``De todas formas, por más que pongas la validación en la UI, de alguna forma hay que implementarlo, y no se aclara nada sobre cómo se haría esa validación. De hecho, faltan relaciones entre entidades de dominio (las cuales sí se detallan) para poder hacer esa validación.``

Haces referencia por ejemplo que para cada TipoPrenda debería tener una lista de Materiales válidos? Y al momento de configurarlo valide contra la misma? 

------

Sobre el código y diagrama:

``Es raro que este método esté en la clase de Uniforme. Si es el Diseñador el que sabe crear cada una de las partes, no sería mejor poder pedirle directamente el uniforme creado y mantener una interfaz más simple?``

Totalmente, me la compliqué solo.

``No habría que validar en algún momento que las prendas que se crean son de la categoría que dicen ser? ``

Esto sí lo pensé en un principio, opté por no sumarlo ya que si no se exponía la interfaz hacia el usuario, y la generación de atuendos era interna, "confiaba" en que los atributos se asignen con el TipoPrenda correspondientes. Si un actor del sistema puede asignarlos manualmente, voy a necesitar esa validación, la sumo para próximas iteraciones.

Gracias nuevamente y saludos!

**Comment by GuidoMartinez** [comment]
Buenas @PalumboN , ya modifique lo indicado anteriormente y me quedaron claras las ventajas de las observaciones.

Me quedaria pendiente la consulta previa:

_``De todas formas, por más que pongas la validación en la UI, de alguna forma hay que implementarlo, y no se aclara nada sobre cómo se haría esa validación. De hecho, faltan relaciones entre entidades de dominio (las cuales sí se detallan) para poder hacer esa validación.``_

**`Haces referencia por ejemplo que para cada TipoPrenda debería tener una lista de Materiales válidos? Y al momento de configurarlo valide contra la misma?`**

Saludos!

**Comment by PalumboN** [comment]
Hola @GuidoMartinez perdón la demora. Sí, hacía referencia a eso (en realidad, a cualquier detalle que aparezca con la implementeación de la validación, creo que era solo ese en este caso).

Saludos y suerte!

**Comment by GuidoMartinez** [comment]
Buenas @PalumboN , nuevamente gracias por el feedback!

Clarísimo! Me hacía ruido en un principio ya que por enunciado no tenemos cuales combinaciones son válidas, como para armar un set/fixture de combinaciones posibles.

Lo tengo en cuenta para próximas iteraciones.

Gracias !
